### ISSUE TITLE
Explore the test data and brainstorm RTDIP component ideas

### ISSUE THREAD

**Issue by luccalb** [amosproj/amos2024ws01-rtdip-data-quality-checker#11]
Explore the test data provided by shell and brainstorm ideas for RTDIP components that ensure better data quality or identify trends/anomalies

**Comment by chris-1187** [comment]
RTDIP component ideas:

Persistent Agent with datastore (Probably pushed back as Shell does not see a need for a DB right now):

- The thought was to instantiate an InfluxDB within the pipeline creation and store monitoring and other data there. InfluxDB is a minimal timeseries DB with a python API and Grafana support (for opt. visualisations).
-  Covered through Issue #26. 


Missing value imputation with imputeFD or MICE through Apache SystemDS (SystemML) integration:
- Apache SystemDS is a ML system for the end-to-end data science lifecycle, including data cleansing
- It runs on top of Apache Spark and can be integrated through it's python bindings
- Optimized for big data and single node operations
- Prerequisite: Flagged missing values -> defined Pattern

Opt. expansion: General SystemDS integration and ability to run any ML algorithm through it's DML (Data Manipulation Language) script language
