### ISSUE TITLE
Clean data based on Interval/Pattern

### ISSUE THREAD

**Issue by mollle** [amosproj/amos2024ws01-rtdip-data-quality-checker#22]
Example Data Timestamps:
00:00
01:00
01:10
02:00

If you expect the data to come in every minute, it would be nice to have an option to get rid of the entry at 01:10, but duplicate detection wont catch it.
Component would get either an interval (e.g. '1min') or a pattern [{'second': 0}, {'second': 13}, {'second': 49}] and a tolerance and allow only one entry in the time frame and delete all other data out of the time frame.
The logic is kind of similar to the identify missing data.

**Comment by dh1542** [comment]
Implemented logic according to description with interval value + unit and tolerance.
