### ISSUE TITLE
Time Series prediction using ARIMA

### ISSUE THREAD

**Issue by luccalb** [amosproj/amos2024ws01-rtdip-data-quality-checker#29]
## User Story

1. As a RTDIP user
2. I want to predict the future development of periodical, time series data, given past values
3. So that I can plan ahead

## Additional context

- Similar to #28 
- A library that could be used: https://www.statsmodels.org/stable/generated/statsmodels.tsa.arima.model.ARIMA.html

## Acceptance Criteria

- Component input
  - past data
  - the name of the column with the data that should be predicted
  - point in time in the future, up to which the data will be generated (or the number of data points to predict in the same interval)
- Component output
  - past data + future predictions 
  - (for all other columns except the predicted one, the values can be empty)
- The component will analyze past time series, and apply the ARIMA model
- The component will generate new data up to a given point of time in the future, using the ARIMA model

## Definition of Done

- Test cases have been created and are running successfully
- Documentation for the new component was added
- Github Actions are running without errors

**Comment by Timm638** [comment]
Next to `statsmodels` the package `pmdarima` seems also to be promising.

**Comment by Timm638** [comment]
Test file for showing visually, that the component is working as intended:
[test_arima_component.txt](https://github.com/user-attachments/files/17718440/test_arima_component.txt)
