### ISSUE TITLE
Prepare RTDIP demo

### ISSUE THREAD

**Issue by luccalb** [amosproj/amos2024ws01-rtdip-data-quality-checker#43]
## User Story

1. As an AMOS PO
2. I want to demo our RTDIP components in a visually appealing way
3. So that people who are unfamiliar with the project get an idea of what it does

## Additional context

- We (the POs) will have to demo the project on "mid-project review" (27.11.2024) and on AMOS demo day (05.02.2025)
- One way to make the demo visually appealing could be to **plot some data** before and after transformation by our components in a **Jupyter notebook**

## Acceptance Criteria

- There exists a demo folder in the repository
- The repository contains a script/jupyter notebook that can be executed
- In the demo the RTDIP library is imported, the same way a real RTDIP engineer would do it
- The data source is free of choice (doesn't have to be Shells data) but should be directly available, either checked into the repository or through a private link
- During the demo plots are shown, not only logs or dataframes are printed out, to make it visually appealing and easier to understand for project outsiders
- Make it as easy as possible for a non-technical PO, ideally just "one click"

## Definition of Done

- Test cases have been created and are running successfully
- Documentation for the new component was added
- Github Actions are running without errors

**Comment by Timm638** [comment]
@sanalmert @luccalb 
What software are you using to view Phython Notebooks?

**Comment by luccalb** [comment]
usually jupyter notebook in vs code or pycharmAm 13.11.2024 13:59 schrieb Timm638 ***@***.***>:
@sanalmert @luccalb
What software are you using to view Phython Notebooks?

**Comment by Timm638** [comment]
@luccalb @sanalmert 
I've drafted up the plots for all components and put it into the notebook located [in the respective branch](https://github.com/amosproj/amos2024ws01-rtdip-data-quality-checker/blob/feature/043_rtdip_demo/notebook/showcase_notebook.ipynb).
Are the plots okay for the upcoming demo? Or should I change something?

**Comment by luccalb** [comment]
@Timm638 @chris-1187 Could you add the ARIMA, and data imputation to the demo as well? I think they are our most "impressive" components.

**Comment by Timm638** [comment]
I finished adding both showcases to the demo.

**Comment by luccalb** [comment]
@FelipeTrost I think linear regression is the only component missing in the demo now. It's not a must, but would definitely be cool to show :)
