### ISSUE TITLE
One-Hot Encoding

### ISSUE THREAD

**Issue by luccalb** [amosproj/amos2024ws01-rtdip-data-quality-checker#45]
## User Story

1. As a RTDIP user
2. I want to one hot encode incoming data
3. So that i can use it for further ML processing

## Acceptance Criteria

- A component exists that
  - receives the name of a column to apply the encoding to
  - receives an optional list of values to encode (one-hot encoding depends on the number of distinct values, having them as input parameter upfront makes it easier, otherwise you would have to identify distinct values from the data, which could be incomplete)
  

## Definition of Done

- Test cases have been created and are running successfully
- Documentation for the new component was added
- Github Actions are running without errors

**Comment by kristen149** [comment]
I move the component to `src\sdk\python\rtdip_sdk\pipelines\transformers\spark\machine_learning\one_hot_encoding.py`
