### ISSUE TITLE
Interval Screening and Missing Entry Insertion

### ISSUE THREAD

**Issue by sanalmert** [amosproj/amos2024ws01-rtdip-data-quality-checker#47]
## User Story

1. As a RTDIP user
2. I want to work only with the data at hand
3. So that we can detect timestamps with missing records / entries 

## Additional context

- The preparing needed to imputate (insert) missing values.
- The incoming data needs to be screened and the interval of datapoints.

## Acceptance Criteria

- Create "empty" records for the missing timestamp with value "NaN"

## Definition of Done

- Test cases have been created and are running successfully
- Documentation for the new component was added
- Github Actions are running without errors

**Comment by chris-1187** [comment]
Closed as redundant subtask
