### ISSUE TITLE
Unified input data validation

### ISSUE THREAD

**Issue by luccalb** [amosproj/amos2024ws01-rtdip-data-quality-checker#60]
## User Story

1. As a RTDIP developer
2. I want make sure the data passed into a component matches certain datatypes
3. So that the component can run smoothly without errors

## Acceptance Criteria

- `DataWrangler` and `DataMonitor` interfaces both define a `validate()` method
- that all components must implement some sort of this function, either generically in a super class or by overriding the `validate()` function themselves
- `validate()` should be called before executing the actual component

## Definition of Done

- Test cases have been created and are running successfully
- Documentation for the new component was added
- Github Actions are running without errors

**Comment by mollle** [comment]
hey, maybe you get an email notification:
do you know when you will finish this? as it doesnt make much sense to start with my refactoring beforehand I would like to plan around that

**Comment by mollle** [comment]
IMHO: The component should be able to handle None, null or "" because we have other components to take care of these missing values. 
So my solution would be to cast all None, nulls and "" to None
