### ISSUE TITLE
Apply feedback on project structure

### ISSUE THREAD

**Issue by luccalb** [amosproj/amos2024ws01-rtdip-data-quality-checker#80]
## Description

- [x] Move **only our components** from `pipelines/data_wranglers` into `pipelines/data_quality/data_manupulation`. Move `pipeline/monitoring` to `pipelines/data_quality/monitoring`.

_Originally posted by @luccalb in https://github.com/amosproj/amos2024ws01-rtdip-data-quality-checker/issues/57#issuecomment-2500789922_

- [x] add copyright text to `sdk/python/rtdip_sdk/pipelines/transformers/spark/machine_learning/__init__.py`

_Originally posted by @TugceOzberkYener in https://github.com/amosproj/amos2024ws01-rtdip-data-quality-checker/pull/57#discussion_r1858188563_

- [x] Rename `ColsToVector` to `ColumnsToVector`

_Originally posted by @TugceOzberkYener in https://github.com/amosproj/amos2024ws01-rtdip-data-quality-checker/pull/57#discussion_r1858189014_

## Acceptance criteria

- All comments regarding general project structure in https://github.com/amosproj/amos2024ws01-rtdip-data-quality-checker/pull/57 have been addressed

## Definition of Done

- Test cases have been created and are running successfully
- Documentation for the new component was added
- Github Actions are running without errors

**Comment by dh1542** [comment]
We will go over develop -> merge-to-clone.
https://github.com/amosproj/amos2024ws01-rtdip-data-quality-checker/pull/83
